language: node_js

sudo: required

services:
  - docker

node_js:
  - "8.12"

script:
  - yarn flow
  - yarn lint
  - yarn test --coverage
  - yarn build
  - git clean -dfx
  - docker build . -t augur_dispute_pool_executor
  - mkdir demo_config && cp config/config.example.json demo_config/config.json
  - docker run -v $(pwd)/demo_config:/src/config augur_dispute_pool_executor printConfig
  - docker run -v $(pwd)/demo_config:/src/config augur_dispute_pool_executor sync
  - docker run -v $(pwd)/demo_config:/src/config augur_dispute_pool_executor printState

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_PUSH_USER" -p="$DOCKER_PUSH_PASSWORD";
      docker tag augur_dispute_pool_executor augurdisputecrowdsourcer/basic-executor;
      docker push augurdisputecrowdsourcer/basic-executor;
    fi
