// flow-typed signature: 82db2831bdd3ebca7ddc4d4b2535dd0c
// flow-typed version: <<STUB>>/augur-dispute-crowdsourcer_vhttps://github.com/burdakovd/augur-dispute-crowdsourcer#1c1bb5d598e260684ab7f3913b5f4fd79fb54d0e/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'augur-dispute-crowdsourcer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'augur-dispute-crowdsourcer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'augur-dispute-crowdsourcer/migrations/1_initial_migration' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/2_deploy_accounting' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/3_deploy_mock_disputer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/4_deploy_mock_crowdsourcer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/5_deploy_disputer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/6_deploy_crowdsourcer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/migrations/7_deploy_instances' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/expectGas' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/scenarios' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestAccounting' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestAccountingFactory' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestCrowdsourcer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestCrowdsourcerFactory' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestDisputerFactory' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestDisputerParamsHashing' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestMockDisputer' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/test/TestMockDisputerFactory' {
  declare module.exports: any;
}

declare module 'augur-dispute-crowdsourcer/truffle-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'augur-dispute-crowdsourcer/migrations/1_initial_migration.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/1_initial_migration'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/2_deploy_accounting.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/2_deploy_accounting'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/3_deploy_mock_disputer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/3_deploy_mock_disputer'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/4_deploy_mock_crowdsourcer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/4_deploy_mock_crowdsourcer'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/5_deploy_disputer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/5_deploy_disputer'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/6_deploy_crowdsourcer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/6_deploy_crowdsourcer'>;
}
declare module 'augur-dispute-crowdsourcer/migrations/7_deploy_instances.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/migrations/7_deploy_instances'>;
}
declare module 'augur-dispute-crowdsourcer/test/expectGas.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/expectGas'>;
}
declare module 'augur-dispute-crowdsourcer/test/scenarios.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/scenarios'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestAccounting.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestAccounting'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestAccountingFactory.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestAccountingFactory'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestCrowdsourcer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestCrowdsourcer'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestCrowdsourcerFactory.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestCrowdsourcerFactory'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestDisputerFactory.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestDisputerFactory'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestDisputerParamsHashing.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestDisputerParamsHashing'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestMockDisputer.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestMockDisputer'>;
}
declare module 'augur-dispute-crowdsourcer/test/TestMockDisputerFactory.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/test/TestMockDisputerFactory'>;
}
declare module 'augur-dispute-crowdsourcer/truffle-config.js' {
  declare module.exports: $Exports<'augur-dispute-crowdsourcer/truffle-config'>;
}
