// flow-typed signature: 09c8cdd81f5e18a80e5a683aa579e121
// flow-typed version: <<STUB>>/log-timestamp_v^0.2.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-timestamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-timestamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'log-timestamp/log-timestamp' {
  declare module.exports: any;
}

declare module 'log-timestamp/tests/format' {
  declare module.exports: any;
}

declare module 'log-timestamp/tests/func' {
  declare module.exports: any;
}

declare module 'log-timestamp/tests/object' {
  declare module.exports: any;
}

declare module 'log-timestamp/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'log-timestamp/log-timestamp.js' {
  declare module.exports: $Exports<'log-timestamp/log-timestamp'>;
}
declare module 'log-timestamp/tests/format.js' {
  declare module.exports: $Exports<'log-timestamp/tests/format'>;
}
declare module 'log-timestamp/tests/func.js' {
  declare module.exports: $Exports<'log-timestamp/tests/func'>;
}
declare module 'log-timestamp/tests/object.js' {
  declare module.exports: $Exports<'log-timestamp/tests/object'>;
}
declare module 'log-timestamp/tests/test.js' {
  declare module.exports: $Exports<'log-timestamp/tests/test'>;
}
