// flow-typed signature: 4a49bd9ae0fb90a9d6ba6ab781490c0e
// flow-typed version: <<STUB>>/sleep-promise_v^8.0.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sleep-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sleep-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sleep-promise/build/cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sleep-promise/build/cjs.js' {
  declare module.exports: $Exports<'sleep-promise/build/cjs'>;
}
